server:
  port: 8870
spring:
  data:
    mongodb:
      username: guest
      password: guest
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.springframework.kafka.support.serialization.JsonDeSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.example.notification.kafka.order.OrderConfirmation,paymentNotification:com.example.notification.kafka.payment.PaymentConfirmation
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest

  mail:
    host: localhost
    port: 1025
    username: guest
    password: guest
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

