server:
  port: 8850

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}



